# Generated by Django 4.2.7 on 2023-11-18 07:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
