# Generated by Django 4.2.7 on 2023-11-20 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0002_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ddapp.record', verbose_name='レコード'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=20, verbose_name='タグ'),
        ),
    ]
