# Generated by Django 4.2.7 on 2023-11-18 07:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0002_alter_record_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='内容'),
        ),
    ]
