# Generated by Django 4.2.7 on 2023-11-20 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0003_tag_tag_record_alter_tag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tag',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_01',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='タグ01'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_02',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='タグ02'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_03',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='タグ03'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_04',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='タグ04'),
        ),
    ]
