# Generated by Django 4.2.7 on 2023-11-21 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ddapp', '0005_alter_tag_tag_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='ddapp.record', verbose_name='レコード'),
        ),
    ]
