# Generated by Django 4.2.7 on 2023-11-23 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddapp', '0006_alter_tag_tag_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(blank=True, null=True, verbose_name='いいね')),
                ('like_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='ddapp.record', verbose_name='レコード')),
                ('like_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
        ),
    ]
