# Generated by Django 4.2.7 on 2023-11-23 05:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddapp', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='いいね'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ddapp.record', verbose_name='レコード'),
        ),
        migrations.AlterField(
            model_name='like',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
