# Generated by Django 4.2.7 on 2023-11-25 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ddapp', '0008_alter_like_like_alter_like_like_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like_user',
        ),
        migrations.AddField(
            model_name='like',
            name='like_from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL, verbose_name='from'),
        ),
        migrations.AddField(
            model_name='like',
            name='like_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL, verbose_name='to'),
        ),
    ]
